#!/usr/bin/env bash

set -euo pipefail

build_and_install() {
    cmake -S . -B build -DCMAKE_POSITION_INDEPENDENT_CODE=ON \
        -DLIBCPUID_ENABLE_TESTS=OFF -DBUILD_SHARED_LIBS=OFF \
        -DLIBCPUID_BUILD_DRIVERS=OFF -DCMAKE_BUILD_TYPE=Release \
        -GNinja -DCMAKE_INSTALL_PREFIX=$HOME/.local
    ninja -C build install
}

prepare_source() {
    DIR=cpuid
    cd /tmp
    [ -d ./${DIR} ] && rm -rf ./${DIR}
    mkdir ${DIR}

    LIBCPUID_RELEASE="${LIBCPUID_RELEASE:-v0.8.1}"

    curl -Ls "https://github.com/anrieff/libcpuid/archive/${LIBCPUID_RELEASE}.tar.gz" | \

    tar xzvf - -C ${DIR}/ --strip-components=1
    cd ${DIR}
}

prepare_source
build_and_install
